version: '3.8'
services:
  web:
    build: .
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    links:
      - mariadb
  mariadb:
    image: mariadb:10.6
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb-pass
      - MYSQL_DATABASE=shopify
